### ISSUE TITLE
one-var rule should be 'never'

### ISSUE THREAD

**Issue by jhecking** [isiahmeadows/eslint-config-npm#2]
This is implicit from the code: The example at https://docs.npmjs.com/misc/coding-style#comma-first is the only place (I could find) where a single variable declaration is used to declare multiple variables. In the code itself npm uses one variable declaration for each variable defined. Should we change the `one-var` rule to

```
'one-var': [2, 'never']
```

?

**Comment by dead-claudia** [comment]
I see.

**Comment by dead-claudia** [comment]
Keep in mind, I'm not actively using this module, and it was more of an experiment than anything else.

**Comment by jhecking** [comment]
If you want, you can add me as a collaborator here on github and npmjs.com and I can help maintain the package. But I don't think there would be many changes going forward anyway.

**Comment by dead-claudia** [comment]
I deprecated the package, anyways. npm uses Standard. https://standardjs.com

**Comment by jhecking** [comment]
Thanks for the pointer! I'll take a look at the `standard` package to replace our current `eslint`/`eslint-config-npm` setup.
